name: Rust

on:
  push:
    branches: [ "test1" ]
  pull_request:
    branches: [ "test1" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-gnu]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --target ${{ matrix.target }}
    - name: Run tests
      run: cargo test --verbose
